name: koi_printer
description: >-
  Flutter printer SDK for ESC/POS, TSPL, CPCL protocols.
  Supports BLE, Classic Bluetooth, TCP/IP, and USB connections
  with template engine and WYSIWYG preview.
version: 0.1.0
repository: https://github.com/mrkoi-is/koi_printer/tree/main/koi_printer
homepage: https://github.com/mrkoi-is/koi_printer
issue_tracker: https://github.com/mrkoi-is/koi_printer/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
      ios:
  koi_printer_command:
    path: ../koi_printer_command
  koi_printer_connection:
    path: ../koi_printer_connection
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
