name: koi_printer_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  koi_printer:
    path: ../koi_printer
  koi_printer_command:
    path: ../koi_printer_command
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/templates/
  fonts:
    - family: SarasaMono
      fonts:
        - asset: assets/fonts/sarasa-mono-sc-regular.ttf
