import 'package:koi_printer/koi_printer.dart';
import 'package:koi_printer_editor/state/editor_state.dart';

int _idCounter = 0;
String _genId() => '${DateTime.now().microsecondsSinceEpoch}_${_idCounter++}';

// ═══════════════════════════════════════════════════════════
// 模板清单库 — 每个模板携带完整的元数据 + Schema + 分组
// ═══════════════════════════════════════════════════════════

final List<KoiTemplateManifest> templateManifests = [
  // ── 寄件客户联 (TMS) ──
  KoiTemplateManifest(
    id: 'tms_sender_v1',
    name: '寄件客户联 (TMS)',
    category: 'tms',
    description: '标准物流寄件面单，含条码、二维码、运费明细、收发件人信息',
    schema: const [
      KoiTemplateField(key: 'companyName', label: '公司名称'),
      KoiTemplateField(key: 'companyAdv', label: '宣传语'),
      KoiTemplateField(key: 'fromNodeInfo', label: '发件网点'),
      KoiTemplateField(key: 'toNodeInfo', label: '目的网点'),
      KoiTemplateField(key: 'ticketSn', label: '运单号'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
      KoiTemplateField(key: 'operatorName', label: '操作员'),
      KoiTemplateField(key: 'startDate', label: '开单时间'),
      KoiTemplateField(key: 'recieverName', label: '收件人'),
      KoiTemplateField(key: 'recieverPhone', label: '收件电话'),
      KoiTemplateField(key: 'pickMethod', label: '取件方式'),
      KoiTemplateField(key: 'senderInfo', label: '发件人'),
      KoiTemplateField(key: 'senderPhone', label: '发件电话'),
      KoiTemplateField(key: 'weight', label: '重量'),
      KoiTemplateField(key: 'volume', label: '体积'),
      KoiTemplateField(key: 'cargoInfo', label: '品名'),
      KoiTemplateField(key: 'cargoCount', label: '件数'),
      KoiTemplateField(key: 'freightFee', label: '应收运费'),
      KoiTemplateField(key: 'preFreightFee', label: '现付运费'),
      KoiTemplateField(key: 'settlementMethod', label: '结算方式'),
      KoiTemplateField(key: 'pickFee', label: '接货费'),
      KoiTemplateField(key: 'psFee', label: '派送费'),
      KoiTemplateField(key: 'totalFee', label: '总运费'),
      KoiTemplateField(key: 'remark', label: '备注'),
    ],
    groups: const [
      KoiTemplateGroup(label: '标题区', startIndex: 0, endIndex: 3),
      KoiTemplateGroup(label: '条码 & 单号', startIndex: 4, endIndex: 7),
      KoiTemplateGroup(label: '收发件人信息', startIndex: 8, endIndex: 10),
      KoiTemplateGroup(label: '费用明细', startIndex: 11, endIndex: 14),
      KoiTemplateGroup(label: '底部', startIndex: 15, endIndex: 16),
    ],
    mockData: const {
      'companyName': '顺丰速运 (SF Express)',
      'companyAdv': '一站式供应链解决方案提供商',
      'fromNodeInfo': '深圳南山科技园网点',
      'toNodeInfo': '北京朝阳国贸网点',
      'ticketSn': 'SF1234567890123',
      'sequnceId': '0001',
      'operatorName': '张三丰',
      'startDate': '2026-05-04 12:00:00',
      'recieverName': '李四',
      'pickMethod': '派送',
      'recieverPhone': '138****8000',
      'senderInfo': '王五',
      'senderPhone': '139****9000',
      'weight': '2.5',
      'volume': '0.01',
      'cargoInfo': '电子产品',
      'cargoCount': '1',
      'freightFee': '18.00',
      'preFreightFee': '18.00',
      'settlementMethod': '现付',
      'pickFee': '0.00',
      'psFee': '0.00',
      'totalFee': '18.00',
      'remark': '易碎物品，请轻拿轻放',
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: '{{companyName}}', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '{{companyAdv}}', align: KoiTextAlign.center),
      KoiTextElement(text: '发货: {{fromNodeInfo}}'),
      KoiTextElement(text: '收货: {{toNodeInfo}}'),
      KoiDividerElement(),
      KoiBarcodeElement(data: '{{ticketSn}}', align: KoiTextAlign.center),
      KoiTextRowElement(columns: [KoiTextColumn(text: '运单号: {{ticketSn}}', ratio: 1), KoiTextColumn(text: '流水号: {{sequnceId}}', ratio: 1)]),
      KoiTextRowElement(columns: [KoiTextColumn(text: '操作员: {{operatorName}}', ratio: 1), KoiTextColumn(text: '{{startDate}}', ratio: 1)]),
      KoiTextElement(text: '收货人: {{recieverName}} [{{pickMethod}}] {{recieverPhone}}', bold: true),
      KoiTextElement(text: '发货人: {{senderInfo}} {{senderPhone}}'),
      KoiTextElement(text: '货物: {{weight}}吨 {{volume}}方 {{cargoInfo}} 合计:{{cargoCount}}'),
      KoiDividerElement(char: '-'),
      KoiTextRowElement(columns: [KoiTextColumn(text: '应收运费: {{freightFee}}', ratio: 1), KoiTextColumn(text: '现付运费: {{preFreightFee}}', ratio: 1), KoiTextColumn(text: '结算: {{settlementMethod}}', ratio: 1)]),
      KoiTextRowElement(columns: [KoiTextColumn(text: '接货费: {{pickFee}}', ratio: 1), KoiTextColumn(text: '派送费: {{psFee}}', ratio: 1)]),
      KoiTextElement(text: '总计总额: {{totalFee}}', bold: true, size: KoiTextSize.size2),
      KoiDividerElement(char: '-'),
      KoiTextElement(text: '备注: {{remark}}'),
      KoiQrCodeElement(data: '{{ticketSn}}', align: KoiTextAlign.center),
      KoiCutElement(),
    ]),
  ),

  // ── 提货客户联 (TMS 完整版) ──
  KoiTemplateManifest(
    id: 'tms_receiver_client_v2',
    name: '提货客户联 (TMS)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印完整提货客户联，含费用明细',
    schema: const [
      KoiTemplateField(key: 'companyName', label: '公司名称'),
      KoiTemplateField(key: 'fromNodeInfo', label: '发货网点'),
      KoiTemplateField(key: 'toNodeInfo', label: '收货网点'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
      KoiTemplateField(key: 'nodeRoleInfo', label: '节点班次'),
      KoiTemplateField(key: 'operatorInfo', label: '操作员'),
      KoiTemplateField(key: 'ticketSn', label: '运单号'),
      KoiTemplateField(key: 'startDate', label: '发货日期'),
      KoiTemplateField(key: 'senderInfo', label: '发货人'),
      KoiTemplateField(key: 'senderPhone', label: '发货电话'),
      KoiTemplateField(key: 'recieverName', label: '收货人'),
      KoiTemplateField(key: 'recieverPhone', label: '收货电话'),
      KoiTemplateField(key: 'pickMethod', label: '提货方式'),
      KoiTemplateField(key: 'cargoInfo', label: '货物'),
      KoiTemplateField(key: 'cargoCount', label: '件数'),
      KoiTemplateField(key: 'preFreightFee', label: '现付运费'),
      KoiTemplateField(key: 'unpaidFreight', label: '到付运费'),
      KoiTemplateField(key: 'pickFee', label: '接货费'),
      KoiTemplateField(key: 'psFee', label: '派送费'),
      KoiTemplateField(key: 'behalfFee', label: '代收'),
      KoiTemplateField(key: 'transFee', label: '分拨费'),
      KoiTemplateField(key: 'extFee', label: '垫付费'),
      KoiTemplateField(key: 'settlementMethod', label: '结算方式'),
      KoiTemplateField(key: 'downReceivableTotalFee', label: '提货应收'),
    ],
    mockData: const {
      'companyName': '顺丰速运',
      'fromNodeInfo': '深圳南山科技园',
      'toNodeInfo': '北京朝阳国贸',
      'sequnceId': '0001',
      'nodeRoleInfo': '深圳->北京 A班',
      'operatorInfo': '001[张三]',
      'ticketSn': 'SF1234567890123',
      'startDate': '2026-05-04',
      'senderInfo': '王五',
      'senderPhone': '139****9000',
      'recieverName': '李四',
      'recieverPhone': '138****8000',
      'pickMethod': '派送',
      'cargoInfo': '电子产品',
      'cargoCount': '1',
      'preFreightFee': '18.00',
      'unpaidFreight': '0.00',
      'pickFee': '0.00',
      'psFee': '5.00',
      'behalfFee': '0.00',
      'transFee': '0.00',
      'extFee': '0.00',
      'settlementMethod': '现付',
      'downReceivableTotalFee': '23.00',
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: '{{companyName}}', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '发货: {{fromNodeInfo}}'),
      KoiTextElement(text: '收货: {{toNodeInfo}}'),
      KoiTextElement(text: '---提货客户联---', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '流水号: {{sequnceId}}', bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '{{nodeRoleInfo}}', bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '操作员: {{operatorInfo}}'),
      KoiTextElement(text: '运单号: {{ticketSn}}'),
      KoiTextElement(text: '发货日期: {{startDate}}'),
      KoiTextElement(text: '发货人: {{senderInfo}} {{senderPhone}}'),
      KoiTextElement(text: '收货人'),
      KoiTextElement(text: '{{recieverName}} {{recieverPhone}}', bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '提货方式: {{pickMethod}}'),
      KoiTextElement(text: '{{cargoInfo}} 合计: {{cargoCount}}', bold: true, size: KoiTextSize.size2),
      KoiDividerElement(),
      KoiTextRowElement(columns: [KoiTextColumn(text: '现付运费: {{preFreightFee}}', ratio: 1), KoiTextColumn(text: '到付运费: {{unpaidFreight}}', ratio: 1)]),
      KoiTextRowElement(columns: [KoiTextColumn(text: '接货费: {{pickFee}}', ratio: 1), KoiTextColumn(text: '派送费: {{psFee}}', ratio: 1)]),
      KoiTextRowElement(columns: [KoiTextColumn(text: '代收: {{behalfFee}}', ratio: 1), KoiTextColumn(text: '分拨费: {{transFee}}', ratio: 1), KoiTextColumn(text: '垫付费: {{extFee}}', ratio: 1)]),
      KoiTextElement(text: '结算方式: {{settlementMethod}}', bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '提货应收: {{downReceivableTotalFee}}', bold: true, size: KoiTextSize.size2),
      KoiDividerElement(),
      KoiSpacerElement(lines: 2),
      KoiCutElement(),
    ]),
  ),

  // ── 发货存根联 (TMS) ──
  KoiTemplateManifest(
    id: 'tms_sender_sub_v1',
    name: '发货存根联 (TMS)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印发货存根联，含开拓费',
    schema: const [
      KoiTemplateField(key: 'ticketSn', label: '运单号'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
      KoiTemplateField(key: 'nodeRoleInfo', label: '节点班次'),
      KoiTemplateField(key: 'operatorName', label: '操作员'),
      KoiTemplateField(key: 'startDate', label: '开单时间'),
      KoiTemplateField(key: 'recieverName', label: '收货人'),
      KoiTemplateField(key: 'recieverPhone', label: '收货电话'),
      KoiTemplateField(key: 'pickMethod', label: '取件方式'),
      KoiTemplateField(key: 'senderInfo', label: '发货人'),
      KoiTemplateField(key: 'senderPhone', label: '发货电话'),
      KoiTemplateField(key: 'cargoInfo', label: '货物'),
      KoiTemplateField(key: 'cargoCount', label: '件数'),
      KoiTemplateField(key: 'freightFee', label: '应收运费'),
      KoiTemplateField(key: 'preFreightFee', label: '现付运费'),
      KoiTemplateField(key: 'settlementMethod', label: '结算方式'),
      KoiTemplateField(key: 'rebateFee', label: '开拓费'),
      KoiTemplateField(key: 'remark', label: '备注'),
    ],
    mockData: const {
      'ticketSn': 'SF1234567890123',
      'sequnceId': '0001',
      'nodeRoleInfo': '深圳->北京 A班',
      'operatorName': '张三',
      'startDate': '2026-05-04 12:00',
      'recieverName': '李四',
      'recieverPhone': '138****8000',
      'pickMethod': '派送',
      'senderInfo': '王五',
      'senderPhone': '139****9000',
      'cargoInfo': '电子产品',
      'cargoCount': '1',
      'freightFee': '18.00',
      'preFreightFee': '18.00',
      'settlementMethod': '现付',
      'rebateFee': '2.00',
      'remark': '易碎物品请轻拿轻放',
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: '发货存根联', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '此联不作为发货和领取代收款凭证!'),
      KoiTextRowElement(columns: [KoiTextColumn(text: '运单号: {{ticketSn}}', ratio: 1), KoiTextColumn(text: '流水号: {{sequnceId}}', ratio: 1)]),
      KoiTextElement(text: '{{nodeRoleInfo}}'),
      KoiTextRowElement(columns: [KoiTextColumn(text: '操作员: {{operatorName}}', ratio: 1), KoiTextColumn(text: '{{startDate}}', ratio: 1)]),
      KoiTextElement(text: '收货人: {{recieverName}} [{{pickMethod}}] {{recieverPhone}}', bold: true),
      KoiTextElement(text: '发货人: {{senderInfo}} {{senderPhone}}'),
      KoiTextElement(text: '货物: {{cargoInfo}} 合计: {{cargoCount}}'),
      KoiDividerElement(char: '-'),
      KoiTextRowElement(columns: [KoiTextColumn(text: '应收运费: {{freightFee}}', ratio: 1), KoiTextColumn(text: '现付运费: {{preFreightFee}}', ratio: 1), KoiTextColumn(text: '结算: {{settlementMethod}}', ratio: 1)]),
      KoiDividerElement(),
      KoiTextElement(text: '开拓费: {{rebateFee}}'),
      KoiTextElement(text: '备注: {{remark}}'),
      KoiQrCodeElement(data: '{{ticketSn}}', align: KoiTextAlign.center),
      KoiSpacerElement(lines: 2),
      KoiCutElement(),
    ]),
  ),

  // ── 原返取货单 (TMS) ──
  KoiTemplateManifest(
    id: 'tms_back_ticket_v1',
    name: '原返取货单 (TMS)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印原返取货单，含客户联和存根联',
    schema: const [
      KoiTemplateField(key: 'companyName', label: '公司名称'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
      KoiTemplateField(key: 'fromNodeName', label: '发站'),
      KoiTemplateField(key: 'toNodeName', label: '目的站'),
      KoiTemplateField(key: 'roleName', label: '班次'),
      KoiTemplateField(key: 'operatorId', label: '操作员编号'),
      KoiTemplateField(key: 'ticketSn', label: '运单号'),
      KoiTemplateField(key: 'startDate', label: '开单时间'),
      KoiTemplateField(key: 'senderInfo', label: '发货人'),
      KoiTemplateField(key: 'recieverName', label: '收货人'),
      KoiTemplateField(key: 'cargoInfo', label: '货物'),
      KoiTemplateField(key: 'cargoCount', label: '件数'),
      KoiTemplateField(key: 'remark', label: '备注'),
    ],
    mockData: const {
      'companyName': '顺丰速运',
      'sequnceId': '0001',
      'fromNodeName': '深圳南山',
      'toNodeName': '北京朝阳',
      'roleName': 'A班',
      'operatorId': '001',
      'ticketSn': 'SF1234567890123',
      'startDate': '2026-05-04 12:00',
      'senderInfo': '王五',
      'recieverName': '李四',
      'cargoInfo': '电子产品',
      'cargoCount': '3',
      'remark': '原返退件',
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: '{{companyName}}', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '原返取货客户联', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '{{sequnceId}}', bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '{{fromNodeName}}->{{toNodeName}} / {{roleName}}', bold: true, size: KoiTextSize.size2),
      KoiTextRowElement(columns: [KoiTextColumn(text: '操作员', ratio: 1), KoiTextColumn(text: '{{operatorId}}', ratio: 3)]),
      KoiTextRowElement(columns: [KoiTextColumn(text: '运单号', ratio: 1), KoiTextColumn(text: '{{ticketSn}}', ratio: 2), KoiTextColumn(text: '{{startDate}}', ratio: 2)]),
      KoiTextElement(text: '发货人: {{senderInfo}}', bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '收货人: {{recieverName}}', bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '货物: {{cargoInfo}} 共{{cargoCount}}件', bold: true, size: KoiTextSize.size2),
      KoiDividerElement(),
      KoiSpacerElement(lines: 2),
      KoiCutElement(),
    ]),
  ),

  // ── 代收发放明细 (TMS) ──
  KoiTemplateManifest(
    id: 'tms_issued_v1',
    name: '代收发放明细 (TMS)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印代收发放明细单，含 ForEach 明细',
    schema: const [
      KoiTemplateField(key: 'companyName', label: '公司名称'),
      KoiTemplateField(key: 'nodeName', label: '网点'),
      KoiTemplateField(key: 'operatorName', label: '操作员'),
      KoiTemplateField(key: 'date', label: '日期'),
      KoiTemplateField(key: 'client', label: '领款人'),
      KoiTemplateField(key: 'method', label: '领款方式'),
      KoiTemplateField(key: 'totalCount', label: '单数'),
      KoiTemplateField(key: 'totalPrice', label: '代收款合计'),
      KoiTemplateField(key: 'procedureFee', label: '手续费'),
      KoiTemplateField(key: 'deductibleFee', label: '抵扣'),
      KoiTemplateField(key: 'issuedFee', label: '结算金额'),
      KoiTemplateField(key: 'items', label: '明细列表', type: KoiFieldType.array),
    ],
    mockData: const {
      'companyName': '顺丰速运',
      'nodeName': '深圳南山科技园',
      'operatorName': '张三',
      'date': '2026-05-04',
      'client': '李四',
      'method': '现金',
      'totalCount': '3',
      'totalPrice': '1500.00',
      'procedureFee': '15.00',
      'deductibleFee': '0.00',
      'issuedFee': '1485.00',
      'items': [
        {'ticketSN': 'SF001', 'receiverName': '王五', 'behalfFee': '500.00'},
        {'ticketSN': 'SF002', 'receiverName': '赵六', 'behalfFee': '600.00'},
        {'ticketSN': 'SF003', 'receiverName': '钱七', 'behalfFee': '400.00'},
      ],
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: '{{companyName}}代收发放明细', align: KoiTextAlign.center),
      KoiTextElement(text: '网点: {{nodeName}}'),
      KoiTextElement(text: '操作员: {{operatorName}}'),
      KoiTextElement(text: '日期: {{date}}'),
      KoiTextElement(text: '领款方式: {{method}}  领款人: {{client}}'),
      KoiDividerElement(),
      KoiTextRowElement(columns: [KoiTextColumn(text: '货号', ratio: 5), KoiTextColumn(text: '收货人', ratio: 3), KoiTextColumn(text: '代收', ratio: 3)]),
      KoiDividerElement(),
      KoiTicketForEachElement(listKey: 'items', templates: [
        KoiTextRowElement(columns: [KoiTextColumn(text: '{{ticketSN}}', ratio: 5), KoiTextColumn(text: '{{receiverName}}', ratio: 3), KoiTextColumn(text: '{{behalfFee}}', ratio: 3)]),
      ]),
      KoiDividerElement(),
      KoiTextRowElement(columns: [KoiTextColumn(text: '合计: {{totalCount}}单', ratio: 1), KoiTextColumn(text: '代收款: {{totalPrice}}', ratio: 1)]),
      KoiTextRowElement(columns: [KoiTextColumn(text: '手续费: {{procedureFee}}', ratio: 1), KoiTextColumn(text: '抵扣: {{deductibleFee}}', ratio: 1)]),
      KoiTextElement(text: '结算: {{issuedFee}}', bold: true, size: KoiTextSize.size2),
      KoiSpacerElement(lines: 2),
      KoiCutElement(),
    ]),
  ),

  // ── 缴款明细 (TMS) ──
  KoiTemplateManifest(
    id: 'tms_payment_v1',
    name: '缴款明细 (TMS)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印缴款明细单，含 ForEach 对账表',
    schema: const [
      KoiTemplateField(key: 'companyName', label: '公司名称'),
      KoiTemplateField(key: 'type', label: '缴款类型'),
      KoiTemplateField(key: 'nodeName', label: '网点'),
      KoiTemplateField(key: 'operatorName', label: '操作员'),
      KoiTemplateField(key: 'date', label: '日期'),
      KoiTemplateField(key: 'totalPrice', label: '合计'),
      KoiTemplateField(key: 'items', label: '缴款明细', type: KoiFieldType.array),
    ],
    mockData: const {
      'companyName': '顺丰速运',
      'type': '运费',
      'nodeName': '深圳南山科技园',
      'operatorName': '张三',
      'date': '2026-05-04',
      'totalPrice': '2350.00',
      'items': [
        {'ticketSN': 'SF001', 'freightFee': '18.00', 'behalfFee': '500.00', 'extFee': '0.00', 'preFreightFee': '18.00'},
        {'ticketSN': 'SF002', 'freightFee': '25.00', 'behalfFee': '600.00', 'extFee': '5.00', 'preFreightFee': '25.00'},
      ],
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: '{{companyName}}', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '{{type}}缴款明细', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '网点: {{nodeName}}'),
      KoiTextElement(text: '操作员: {{operatorName}}'),
      KoiTextElement(text: '日期: {{date}}'),
      KoiDividerElement(),
      KoiTextRowElement(columns: [KoiTextColumn(text: '单号', ratio: 3), KoiTextColumn(text: '运费', ratio: 2), KoiTextColumn(text: '代收', ratio: 3), KoiTextColumn(text: '垫付', ratio: 2), KoiTextColumn(text: '现付', ratio: 2)]),
      KoiDividerElement(),
      KoiTicketForEachElement(listKey: 'items', templates: [
        KoiTextRowElement(columns: [KoiTextColumn(text: '{{ticketSN}}', ratio: 3), KoiTextColumn(text: '{{freightFee}}', ratio: 2), KoiTextColumn(text: '{{behalfFee}}', ratio: 3), KoiTextColumn(text: '{{extFee}}', ratio: 2), KoiTextColumn(text: '{{preFreightFee}}', ratio: 2)]),
      ]),
      KoiDividerElement(),
      KoiTextElement(text: '合计: {{totalPrice}}', bold: true, size: KoiTextSize.size2),
      KoiSpacerElement(lines: 5),
      KoiCutElement(),
    ]),
  ),

  // ── 交款单 (Finance) ──
  KoiTemplateManifest(
    id: 'finance_handover_v1',
    name: '交款单 (Finance)',
    category: 'finance',
    description: '财务交款单，含业务员交接明细列表 (ForEach)',
    schema: const [
      KoiTemplateField(key: 'nodeInfo', label: '网点信息'),
      KoiTemplateField(key: 'bizerName', label: '业务员'),
      KoiTemplateField(key: 'handUser', label: '交款人'),
      KoiTemplateField(key: 'handDate', label: '交款时间'),
      KoiTemplateField(key: 'totalAmount', label: '总计金额'),
      KoiTemplateField(key: 'items', label: '交接明细列表', type: KoiFieldType.array),
    ],
    groups: const [
      KoiTemplateGroup(label: '标题 & 信息', startIndex: 0, endIndex: 4),
      KoiTemplateGroup(label: '明细列表', startIndex: 5, endIndex: 8),
      KoiTemplateGroup(label: '合计', startIndex: 9, endIndex: 10),
    ],
    mockData: const {
      'nodeInfo': '深圳高新园财务中心',
      'bizerName': '李四',
      'handUser': '王五',
      'handDate': '2026-05-04 18:00',
      'totalAmount': '¥ 50,000',
      'items': [
        {'name': '顺丰特快', 'count': 100, 'amount': '¥1,800'},
        {'name': '顺丰标快', 'count': 500, 'amount': '¥6,000'},
        {'name': '包装费', 'count': 100, 'amount': '¥500'},
      ],
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: '交款单', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '网点: {{nodeInfo}}', align: KoiTextAlign.center),
      KoiDividerElement(),
      KoiTextRowElement(columns: [KoiTextColumn(text: '业务员: {{bizerName}}', ratio: 1), KoiTextColumn(text: '交款人: {{handUser}}', ratio: 1)]),
      KoiTextElement(text: '交款时间: {{handDate}}'),
      KoiDividerElement(char: '-'),
      KoiTextRowElement(columns: [KoiTextColumn(text: '项目', ratio: 6), KoiTextColumn(text: '票数', ratio: 2, align: KoiTextAlign.center), KoiTextColumn(text: '金额', ratio: 4, align: KoiTextAlign.right)]),
      KoiDividerElement(char: '-'),
      KoiTicketForEachElement(listKey: 'items', templates: [
        KoiTextRowElement(columns: [KoiTextColumn(text: '{{name}}', ratio: 6), KoiTextColumn(text: '{{count}}', ratio: 2, align: KoiTextAlign.center), KoiTextColumn(text: '{{amount}}', ratio: 4, align: KoiTextAlign.right)]),
      ]),
      KoiDividerElement(char: '-'),
      KoiTextElement(text: '总计交款: {{totalAmount}}', bold: true, size: KoiTextSize.size2),
      KoiCutElement(),
    ]),
  ),

  // ── 请款单 (Payment) ──
  KoiTemplateManifest(
    id: 'payment_request_v1',
    name: '请款单 (Payment)',
    category: 'payment',
    description: '请款申请单，含审批签字留白',
    schema: const [
      KoiTemplateField(key: 'requestUser', label: '请款人'),
      KoiTemplateField(key: 'requestAmount', label: '请款金额'),
      KoiTemplateField(key: 'reason', label: '请款事由'),
    ],
    mockData: const {
      'requestUser': '赵六',
      'requestAmount': '¥ 5,000.00',
      'reason': '采购新一批打印纸和碳带',
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: '请款单', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '请款人: {{requestUser}}'),
      KoiTextElement(text: '请款金额: {{requestAmount}}', bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: '请款事由: {{reason}}'),
      KoiSpacerElement(lines: 2),
      KoiTextRowElement(columns: [KoiTextColumn(text: '审批人签字:', ratio: 1), KoiTextColumn(text: '财务签字:', ratio: 1)]),
      KoiSpacerElement(lines: 3),
      KoiCutElement(),
    ]),
  ),

  // ── 简单收据 (Demo) ──
  KoiTemplateManifest(
    id: 'demo_receipt_v1',
    name: '简单收据 (Demo)',
    category: 'demo',
    description: '演示模板，含 ForEach 商品循环和二维码',
    schema: const [
      KoiTemplateField(key: 'fee.total', label: '合计金额'),
      KoiTemplateField(key: 'items', label: '商品列表', type: KoiFieldType.array),
    ],
    mockData: const {
      'fee': {'total': 188.0},
      'items': [
        {'name': 'Koi 机械键盘', 'qty': 1, 'price': 99.0},
        {'name': 'Type-C 数据线', 'qty': 2, 'price': 19.9},
      ],
    },
    document: KoiTicketDocument(elements: [
      KoiTextElement(text: 'Mr.Koi Store', align: KoiTextAlign.center, bold: true, size: KoiTextSize.size2),
      KoiTextElement(text: 'www.mrkoi.com', align: KoiTextAlign.center),
      KoiDividerElement(),
      KoiTextRowElement(columns: [KoiTextColumn(text: '商品', ratio: 6), KoiTextColumn(text: '数量', ratio: 2, align: KoiTextAlign.center), KoiTextColumn(text: '金额', ratio: 4, align: KoiTextAlign.right)]),
      KoiDividerElement(char: '-'),
      KoiTicketForEachElement(listKey: 'items', templates: [
        KoiTextRowElement(columns: [KoiTextColumn(text: '{{name}}', ratio: 6), KoiTextColumn(text: '{{qty}}', ratio: 2, align: KoiTextAlign.center), KoiTextColumn(text: '{{price}}', ratio: 4, align: KoiTextAlign.right)]),
      ]),
      KoiDividerElement(),
      KoiTextRowElement(columns: [KoiTextColumn(text: '合计', ratio: 8, bold: true), KoiTextColumn(text: '¥{{fee.total}}', ratio: 4, align: KoiTextAlign.right)]),
      KoiSpacerElement(lines: 1),
      KoiQrCodeElement(data: 'https://mrkoi.io', align: KoiTextAlign.center, size: KoiQrSize.size5),
      KoiCutElement(),
    ]),
  ),

  // ── 茶饮杯贴标签 (Label) ──
  KoiTemplateManifest(
    id: 'demo_label_v1',
    name: '茶饮杯贴标签 (Label)',
    category: 'demo',
    description: '标准饮品杯贴标签演示，包含绝对定位的文本和框线',
    schema: const [
      KoiTemplateField(key: 'shopName', label: '门店名称'),
      KoiTemplateField(key: 'orderNo', label: '取餐号'),
      KoiTemplateField(key: 'productName', label: '饮品名称'),
      KoiTemplateField(key: 'specs', label: '规格要求'),
      KoiTemplateField(key: 'time', label: '出杯时间'),
    ],
    mockData: const {
      'shopName': 'Koi 奶茶 (科技园店)',
      'orderNo': 'A082',
      'productName': '招牌波霸奶茶',
      'specs': '少冰 / 半糖 / 加仙草',
      'time': '2026-05-04 14:30',
    },
    document: KoiLabelDocument(elements: [
      KoiLabelSetupElement(widthMm: 40, heightMm: 30),
      KoiPositionedTextElement(x: 10, y: 10, text: '{{shopName}}'),
      KoiPositionedTextElement(x: 10, y: 40, text: '{{orderNo}}', xScale: 2, yScale: 2, bold: true),
      KoiPositionedTextElement(x: 10, y: 90, text: '{{productName}}', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 10, y: 140, text: '{{specs}}'),
      KoiPositionedTextElement(x: 10, y: 180, text: '时间: {{time}}'),
      KoiLabelBoxElement(x: 5, y: 5, width: 290, height: 215, thickness: 2),
    ]),
  ),

  // ── 达宣标签 (TMS 同步) ──
  KoiTemplateManifest(
    id: 'tms_label_daxuan',
    name: '达宣标签 (TMS同步)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印达宣标签模板',
    schema: const [
      KoiTemplateField(key: 'toNodeName', label: '目的网点'),
      KoiTemplateField(key: 'receiverName', label: '收货人'),
      KoiTemplateField(key: 'totalCount', label: '件数'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
      KoiTemplateField(key: 'startDate', label: '开单时间'),
      KoiTemplateField(key: 'companyInfo', label: '公司网点'),
    ],
    mockData: const {
      'toNodeName': '北京朝阳区',
      'receiverName': '张三丰',
      'totalCount': '3',
      'sequnceId': '00123',
      'startDate': '2026-05-04 12:00:00',
      'companyInfo': '达宣物流 (深圳科苑站)',
    },
    document: KoiLabelDocument(elements: [
      KoiLabelSetupElement(widthMm: 75, heightMm: 50),
      KoiPositionedTextElement(x: 180, y: 10, text: '{{toNodeName}}', xScale: 3, yScale: 3, bold: true),
      KoiPositionedTextElement(x: 10, y: 100, text: '收货人: {{receiverName}}', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 480, y: 100, text: '{{totalCount}}件', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 10, y: 160, text: '流水号: {{sequnceId}}', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 10, y: 220, text: '开单时间: {{startDate}}', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 150, y: 300, text: '{{companyInfo}}', xScale: 1, yScale: 1),
    ]),
  ),

  // ── 伟平标签 (TMS 同步) ──
  KoiTemplateManifest(
    id: 'tms_label_weiping',
    name: '伟平标签 (TMS同步)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印伟平标签模板',
    schema: const [
      KoiTemplateField(key: 'companyName', label: '公司名称'),
      KoiTemplateField(key: 'toNodeName', label: '目的网点'),
      KoiTemplateField(key: 'receiverName', label: '收货人'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
      KoiTemplateField(key: 'totalCount', label: '件数'),
      KoiTemplateField(key: 'fromTime', label: '发站与时间'),
      KoiTemplateField(key: 'staffName', label: '开单人'),
    ],
    mockData: const {
      'companyName': '伟平快运',
      'toNodeName': '广州白云',
      'receiverName': '李四',
      'sequnceId': '00124',
      'totalCount': '5',
      'fromTime': '深圳: 2026-05-04',
      'staffName': '王五',
    },
    document: KoiLabelDocument(elements: [
      KoiLabelSetupElement(widthMm: 75, heightMm: 50),
      KoiPositionedTextElement(x: 10, y: 20, text: '{{companyName}}', xScale: 2, yScale: 2, bold: true),
      KoiPositionedTextElement(x: 360, y: 20, text: '{{toNodeName}}', xScale: 3, yScale: 3, bold: true),
      KoiPositionedTextElement(x: 10, y: 100, text: '{{receiverName}}', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 10, y: 200, text: '{{sequnceId}}', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 360, y: 200, text: '{{totalCount}}件', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 10, y: 280, text: '{{fromTime}}', xScale: 1, yScale: 1),
      KoiPositionedTextElement(x: 360, y: 280, text: '{{staffName}}', xScale: 1, yScale: 1),
    ]),
  ),

  // ── 泰实标签 (TMS 同步) ──
  KoiTemplateManifest(
    id: 'tms_label_taishi',
    name: '泰实标签 (TMS同步)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印泰实物流标签模板 74×45mm',
    schema: const [
      KoiTemplateField(key: 'companyName', label: '公司名称'),
      KoiTemplateField(key: 'fromNodeName', label: '发站'),
      KoiTemplateField(key: 'toNodeName', label: '目的网点'),
      KoiTemplateField(key: 'ticketSn', label: '运单号'),
      KoiTemplateField(key: 'index', label: '件号'),
      KoiTemplateField(key: 'startDate', label: '开单时间'),
      KoiTemplateField(key: 'cargo', label: '品名'),
      KoiTemplateField(key: 'receiverName', label: '收货人'),
      KoiTemplateField(key: 'totalCount', label: '件数'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
    ],
    mockData: const {
      'companyName': '泰实物流',
      'fromNodeName': '深圳科技园',
      'toNodeName': '广州天河',
      'ticketSn': 'TS20260504001',
      'index': '1-3',
      'startDate': '2026-05-04 12:00',
      'cargo': '电子元件',
      'receiverName': '张三',
      'totalCount': '3',
      'sequnceId': '00125',
    },
    document: KoiLabelDocument(elements: [
      KoiLabelSetupElement(widthMm: 74, heightMm: 45),
      KoiPositionedTextElement(x: 80, y: 8, text: '{{companyName}}({{fromNodeName}})', xScale: 1, yScale: 1),
      KoiPositionedTextElement(x: 10, y: 40, text: '{{toNodeName}}', xScale: 5, yScale: 5, bold: true),
      KoiPositionedTextElement(x: 10, y: 130, text: '{{ticketSn}}-{{index}} [{{startDate}}] {{cargo}}', xScale: 1, yScale: 1),
      KoiPositionedTextElement(x: 10, y: 165, text: '{{receiverName}}', xScale: 3, yScale: 3),
      KoiPositionedTextElement(x: 360, y: 165, text: '{{totalCount}}件', xScale: 3, yScale: 3),
      KoiPositionedTextElement(x: 360, y: 220, text: '{{sequnceId}}', xScale: 3, yScale: 3),
    ]),
  ),

  // ── 川速行标签 (TMS 同步) ──
  KoiTemplateManifest(
    id: 'tms_label_chuansuxing',
    name: '川速行标签 (TMS同步)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印川速行标签模板 74×45mm 含条码',
    schema: const [
      KoiTemplateField(key: 'toNodeName', label: '目的网点'),
      KoiTemplateField(key: 'ticketSn', label: '运单号'),
      KoiTemplateField(key: 'index', label: '件号'),
      KoiTemplateField(key: 'fromNodeName', label: '发站'),
      KoiTemplateField(key: 'startDate', label: '开单时间'),
      KoiTemplateField(key: 'receiverName', label: '收货人'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
      KoiTemplateField(key: 'cargo', label: '品名'),
      KoiTemplateField(key: 'companyName', label: '公司名称'),
      KoiTemplateField(key: 'senderName', label: '发货人'),
      KoiTemplateField(key: 'senderPhone', label: '发货电话'),
    ],
    mockData: const {
      'toNodeName': '成都武侯',
      'ticketSn': 'CSX20260504002',
      'index': '1-2',
      'fromNodeName': '深圳南山',
      'startDate': '2026-05-04',
      'receiverName': '李四',
      'sequnceId': '00126',
      'cargo': '服装',
      'companyName': '川速行物流',
      'senderName': '王五',
      'senderPhone': '139****9000',
    },
    document: KoiLabelDocument(elements: [
      KoiLabelSetupElement(widthMm: 74, heightMm: 45),
      KoiPositionedTextElement(x: 120, y: 8, text: '{{toNodeName}}', xScale: 3, yScale: 3, bold: true),
      KoiPositionedBarcodeElement(x: 80, y: 70, data: '{{ticketSn}}'),
      KoiPositionedTextElement(x: 16, y: 170, text: '{{startDate}} [{{fromNodeName}}] {{ticketSn}}-{{index}}', xScale: 1, yScale: 1),
      KoiPositionedTextElement(x: 10, y: 200, text: '{{receiverName}}', xScale: 2, yScale: 2),
      KoiPositionedTextElement(x: 360, y: 200, text: '{{sequnceId}}', xScale: 3, yScale: 3),
      KoiPositionedTextElement(x: 360, y: 260, text: '{{cargo}}', xScale: 1, yScale: 1),
      KoiPositionedTextElement(x: 10, y: 280, text: '{{senderName}} {{senderPhone}}', xScale: 1, yScale: 1),
      KoiPositionedTextElement(x: 300, y: 280, text: '{{companyName}}', xScale: 1, yScale: 1),
    ]),
  ),

  // ── 亿鑫标签 (TMS 同步) ──
  KoiTemplateManifest(
    id: 'tms_label_yixin',
    name: '亿鑫标签 (TMS同步)',
    category: 'tms',
    description: '同步自 TMS 蓝牙打印亿鑫物流标签模板 78×60mm',
    schema: const [
      KoiTemplateField(key: 'receiverName', label: '收货人'),
      KoiTemplateField(key: 'sequnceId', label: '流水号'),
      KoiTemplateField(key: 'totalCount', label: '件数'),
      KoiTemplateField(key: 'toNodeName', label: '目的网点'),
    ],
    mockData: const {
      'receiverName': '赵六',
      'sequnceId': '00127',
      'totalCount': '5',
      'toNodeName': '重庆渝北',
    },
    document: KoiLabelDocument(elements: [
      KoiLabelSetupElement(widthMm: 78, heightMm: 60),
      KoiPositionedTextElement(x: 40, y: 10, text: '{{receiverName}}', xScale: 5, yScale: 5, bold: true),
      KoiPositionedTextElement(x: 80, y: 200, text: '{{sequnceId}}-{{totalCount}}', xScale: 5, yScale: 5, bold: true),
      KoiPositionedTextElement(x: 240, y: 330, text: '{{toNodeName}}', xScale: 4, yScale: 4),
    ]),
  ),
];

// ═══════════════════════════════════════════════════════════
// 编辑器兼容层 — Manifest → EditorElement 转换
// ═══════════════════════════════════════════════════════════

/// 将 Manifest 的 document.elements 转换为编辑器可用的 EditorElement 列表。
List<EditorElement> manifestToEditorElements(KoiTemplateManifest manifest) {
  final doc = manifest.document;
  if (doc is KoiTicketDocument) {
    return doc.elements.map((e) => EditorElement(id: _genId(), element: e)).toList();
  } else if (doc is KoiLabelDocument) {
    return doc.elements.map((e) => EditorElement(id: _genId(), element: e)).toList();
  }
  return [];
}

/// 默认加载的模板 (寄件客户联)。
final KoiTemplateManifest defaultManifest = templateManifests.first;
final List<EditorElement> defaultTemplateElements = manifestToEditorElements(defaultManifest);
