name: koi_printer_connection
description: >
  Printer connection adapters for koi_printer.
  Supports BLE, Classic Bluetooth, and TCP/IP.
version: 0.1.0
repository: https://github.com/mrkoi-is/koi_printer/tree/main/koi_printer_connection
homepage: https://github.com/mrkoi-is/koi_printer
issue_tracker: https://github.com/mrkoi-is/koi_printer/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.0
  flutter_bluetooth_serial: ^0.4.0
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
